baseURL = 'https://robot-one.github.io/'
languageCode = 'en-gb'
defaultContentLanguage = "en"
title = 'Of Machines and Men'
theme = ["dream", "darths-hugo-shortcodes"]


# copyright = ""
googleAnalytics = "G-CGP1Q20XRY"
# disqusShortname = ""
# enableRobotsTXT = true

# recommended for GitHub pages
publishDir = 'docs'

# enable inline html rendering within Markdown posts
[markup.goldmark.renderer] 
unsafe = true 

# ignore stupid error
ignoreErrors = ["error-missing-instagram-accesstoken"]

[params]
  debug= "true"
  backgroundImage = "/img/background.jpg"
  background = "#f7f7f7"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  backgroundDark = "black"
  backgroundImageDark = "/img/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = [""]

  author = "Darthagnon"
  description = "Handcrafted heroes and legends by Darthagnon"
  avatar = "/img/RobotOne.png"
  roundAvatar = false
  headerTitle = "Of Machines and Men"
  motto = "Handcrafted heroes and legends"
  # hideArticleTags = "true"
  maxTags = 12
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  footerBottomText = "Site is a work-in-progress"

  rss = true
  rssHeader = true

  # socials
  # email = "robot@gmail.com"
  # twitter = "DJdeLima"
  # facebook = "darren.delima.5"
  # instagram = "darthagnon"
  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  # socials, deprecated - use /data/socials.toml instead
  # mastodon = ""
  # linkedin = "darrendelima"
  # github = "darthagnon"
  # stackoverflow = "12589363/darth-agnon"
  # codepen = ""
  
  # Add IndieAuth endpoint here, as per https://indieweb.org/IndieAuth#How_to
  indieauth = "https://indieauth.com/auth"

  siteStartYear = 2016
  # Required for "Site last updated" footer
  # commit = "https://github.com/<username>/<siterepo.github.io>/commits/"
  commit = "https://github.com/robot-one/robot-one.github.io/commits/"

  favicon = "/favicons/favicon.ico"

  # true: load 3rd-party JS/CSS from CDN; false: load instead from local files
  CDNJS = false
  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsCDN = "js/3p/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true
  topTags = true
  textButtons = true
  # textButtonsMini = false
  textSocials = true
  
  # Error 404 Not Found page text
  error404Header = "Oops...You are lost in dream."
  error404SubHeader = "Don't worry though, click the button below to wake up."
  
  # Enable/Disable Mac OS X style scrollbars - GLITCHY! Recommended false if using PhotoSwipe
  OverlayScrollbars = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  fixedNav = true
  collapsibleTags = true
  # collapseBySummary = true

  [params.advanced]
    customCSS = ["css/custom.css"] # files in the list will be loaded in order
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
  


# required for Search to work
[outputs]
  home = ["HTML", "RSS", "JSON"]